name: test image

on:
  workflow_call:
    inputs:
      cache-from:
        required: true
        type: string

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: dev/Dockerfile
          platforms: linux/amd64
          # artifacts storage limit suck - use gchr to store temporary image
          # outputs: type=docker,dest=/tmp/myimage.tar
          push: true
          tags: ghcr.io/${{ github.repository }}-builder-cache:${{ github.ref_name }}-test-artifact
          cache-from: |
            ${{ inputs.cache-from }}
            type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:${{ github.ref_name }}-amd64
          # specific "cache-to" here as otherwise it would override the latest multi-platform cache with this amd64-only one
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-builder-cache:${{ github.ref_name }}-amd64,mode=max

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: surface-tests
      #     path: /tmp/myimage.tar
      #     retention-days: 1
